---
- name: Installing P10k with plugins
  hosts: localhost
  gather_facts: false
  become: true

  tasks:  
    - name: Installing Powerlevel10k
      shell: git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
      become_user: abramson
      args:
        warn: false
    #   register: command_output
    
    # - name: Output of editing theme in .zshrc
    #   debug:
    #    var: command_output

    - name: Editing theme in .zshrc
      shell: sed -i 's|ZSH_THEME="bira"|ZSH_THEME="powerlevel10k/powerlevel10k"|g' /home/abramson/.zshrc
      become_user: abramson
      args:
        warn: false
    #   register: command_output
    
    # - name: Output of editing theme in .zshrc
    #   debug:
    #    var: command_output